#! /bin/sh

sxhkd &
feh --bg-fill $HOME/pictures/wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color  "#B5BD68"
bspc config normal_border_color   "#1D1F21"
bspc config presel_feedback_color "#17191B"

bspc config focus_follows_pointer true
bspc config border_width             2
bspc config window_gap              20

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true


