#! /bin/sh

sxhkd &
feh --bg-fill $HOME/pictures/wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color  "#5F9E94"
bspc config normal_border_color   "#2F343F"
bspc config presel_feedback_color "#353945"

bspc config focus_follows_pointer true
bspc config border_width             2
bspc config window_gap              20

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true


