#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap             30
bspc config focus_follows_pointer  true

bspc config split_ratio             0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc config focused_border_color  \#ebcb8b
bspc config normal_border_color   \#2b303b

bspc rule -a URxvt state=pseudo_tiled

panel &
